version: '3.9'

services:
  appjs:
    container_name: appjs
    image: appjs

    build:
      context: js
    ports:
      - '3000:3000'

    environment:
      - EXTERNALPORT=3000

    volumes:
      - files:/app/files

    depends_on:
      - kafka

  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build:
      context: python

    ports:
      - '80:80'
    volumes:
      - files:/app/files

    depends_on:
      - kafka

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - '2181:2181'

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'request:1:1, response-request:1:1'

    links:
      - zookeeper

    depends_on:
      - zookeeper

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  files: {}
  kafka-volume: {}
