version: '3.9'

services:
  appjs:
    container_name: appjs
    image: appjs

    build:
      context: js
    ports:
      - '3000:3000'

    environment:
      - EXTERNALPORT=3000

    volumes:
      - files:/app/files

  pythonapp:
    container_name: pythonapp
    image: pythonapp
    build:
      context: python

    ports:
      - '80:80'
    volumes:
      - files:/app/files

volumes:
  files: {}
